### ISSUE TITLE
Remember.Core 申请加入

### ISSUE THREAD

**Issue by yiyungent** [BaseCoreVueProject/Home#1]
## 项目名称: 

Remember.Core

## 项目地址: 

https://github.com/yiyungent/Remember.Core

## 项目描述: 

ASP.NET Core Web 应用框架，主要提供了插件系统的简单实现，采用前后端分离设计（WebAPI + vue-element-admin），如果你需要实现Web插件系统，或许本项目是不错的参考。

## 未来计划: 

PluginCore
- [ ] 全局组件/实现 可采用 依赖注入 的方式替换
- [ ] PluginCore 打包 发布到nuget（独立出插件核心）

权限管理
- [ ] 基于角色的权限设计 (移植remember方案)

安装向导
- [ ] 友好安装界面

## 联系我

Email: yiyungent@126.com

**Comment by anjoy8** [comment]
已发邀请，同意后，可以fork进来，目前暂排推广第四期。
