### ISSUE TITLE
SimCaptcha 申请加入

### ISSUE THREAD

**Issue by yiyungent** [BaseCoreVueProject/Home#2]
## 项目名称: 

SimCaptcha

## 项目地址: 

https://github.com/yiyungent/SimCaptcha

## 项目描述: 

.NET 实现 点触验证码，前后端均已实现。

## 运行截图

![logo](https://user-images.githubusercontent.com/16939388/97660420-78e67b80-1aac-11eb-8ba2-bc232ca56310.png)

## 未来计划: 

SimCaptcha.AspNetCore

- [ ] 全局依赖注入
- [ ] 所有组件均采用构造器注入，用户可以再次注入来替换组件
- [ ] UseSimCaptcha() 提供扩展,替换选项
- [ ] AddSimCaptcha() 提供扩展,替换选项

## 联系我

Email: yiyungent@126.com

**Comment by anjoy8** [comment]
成员邀请已发出，
同意后，Fork该项目即可完成。

**Comment by yiyungent** [comment]
已完成Fork
