### ISSUE TITLE
SnailAspNetCoreFramework 申请加入

### ISSUE THREAD

**Issue by shengyu-kmust** [BaseCoreVueProject/Home#3]
## 项目介绍
本项目定位为基于asp.net core的中小企业快速开发框架，包含完整的后端和前端的代码。
目前正在开发v2.0版本，v1.0版本可在分支里切换后直接运行，教程可参考我的系列博客，或是项目内的docs
后端技术栈：asp.net core 3.1,cap,swag,ef core code first,autofac,automapper,nlog,aop
前端技术栈：vue-element-admin,crud快速开发模块组件,mock
实现的功能：基于角色的权限控制，项目分层约定，代码自动生成，日志记录，性能监控，aop等
## 项目地址
https://github.com/shengyu-kmust/SnailAspNetCoreFramework
## 补充说明
* 将长期维护升级此项目
* 联系方式373087455@qq.com
* 此项目的公共组件用的是Snail开源项目，地址为https://github.com/shengyu-kmust/Snail

**Comment by anjoy8** [comment]
您好，已经发送邀请，同意后，可以自行Fork到组织，以后定期fork。
代码所有权益不会受到任何影响。
我会在以后的博客园和公众号里推荐，排队中，排队信息可以查看：https://github.com/BaseCoreVueProject/Home#%E6%8E%A8%E5%B9%BF%E6%96%B9%E6%A1%88。

**Comment by Lenceas** [comment]
# 项目介绍
.net 5 api 前后端分离 个人博客
后端技术栈：.net 5,swagger,ef core,sqlsugar,code first,autofac,automapper,log4net,aop,redis...
前端技术栈：打算用element ui + vue2.0全家桶
数据库:mysql+mongodb
实现的功能：仓储模式,异步,自动初始化数据,codefirst,日志aop,简单jwt bearer接口权限

# 项目地址
https://github.com/Lenceas/Lenceas.Blog
https://github.com/Lenceas/LJS.Core

# 补充说明

- 本人毕业2年,技术还比较菜,但是有一颗强烈的想要学习提升自己的心,每晚坚持最少学习2小时
- 联系方式 2923280915@qq.com

**Comment by anjoy8** [comment]
你新开一个issue吧，和这个项目重复了

**Comment by shengyu-kmust** [comment]
ok，已经新开issue
