### ISSUE TITLE
Zero.Core申请加入

### ISSUE THREAD

**Issue by QQ2287991080** [BaseCoreVueProject/Home#4]
### 项目介绍
Zero.Core 适用于快速开发，可以说完全能做到代码clone下来就能跑，后续功能陆续更新。
后端：asp.net core+ef core+jwt+redis+swagger等
前端：element-ui+axios
已开发功能：用户、角色、权限、菜单管理
### 项目地址
后端：https://github.com/QQ2287991080/Zero.Core
前端：https://github.com/QQ2287991080/Zero.Core.Admin
### 补充说明
项目的基础框架已经搭好，后续的功能会继续追加！！！

**Comment by anjoy8** [comment]
您好，已经发送邀请，同意后，可以自行Fork到组织，以后定期同步，一个月一次也行。
**代码所有权益不会受到任何影响**。
我会在以后的公众号里推荐，排队中，排队信息可以查看：https://github.com/BaseCoreVueProject/Home#%E6%8E%A8%E5%B9%BF%E6%96%B9%E6%A1%88。

**Comment by anjoy8** [comment]
项目已入驻，推广安排中
