### ISSUE TITLE
LJS.Core 申请加入

### ISSUE THREAD

**Issue by Lenceas** [BaseCoreVueProject/Home#5]
# 项目介绍
.net 5 api 前后端分离 个人博客
后端技术栈：.net 5,swagger,ef core,sqlsugar,code first,autofac,automapper,log4net,aop,redis...
前端技术栈：打算用element ui + vue2.0全家桶
数据库:mysql+mongodb
实现的功能：仓储模式,异步,自动初始化数据,codefirst,日志aop,简单jwt bearer接口权限

# 项目地址
https://github.com/Lenceas/Lenceas.Blog
https://github.com/Lenceas/LJS.Core

# 补充说明

- 本人毕业2年,技术还比较菜,但是有一颗强烈的想要学习提升自己的心,每晚坚持最少学习2小时
- 联系方式 2923280915@qq.com

**Comment by anjoy8** [comment]
有时间把README完善下吧，你写的有些简单了，
格式，可以仿照我的公众号文章：
https://mp.weixin.qq.com/s/RSn9CUKn1P59wNn29Nravw

不要求排版，只写技术栈和功能就行。

**Comment by Lenceas** [comment]
好的,今晚回去弄一下.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BaseCoreVueProject/Home"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 上午9:57
收件人:&nbsp;"BaseCoreVueProject/Home"<Home@noreply.github.com&gt;;
抄送:&nbsp;"2923280915"<2923280915@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BaseCoreVueProject/Home] LJS.Core 申请加入 (#5)





 
有时间把README完善下吧，你写的有些简单了，
 格式，可以仿照我的公众号文章：
 https://mp.weixin.qq.com/s/RSn9CUKn1P59wNn29Nravw
 
不要求排版，只写技术栈和功能就行。

**Comment by Lenceas** [comment]
老张,我昨晚补充了一下Readme,有时间看下是否ok

**Comment by anjoy8** [comment]
你的博客有在线地址么，可以顺带推广下你的博客地址

**Comment by Lenceas** [comment]
在线地址是学部署的时候丢上去测试的


前端(还没开始弄,就挂了个登录页,数据还没对接api)
http://www.lujiesheng.cn/#/
后端(不是最新的,我本地还在开发)
http://api.lujiesheng.cn/index.html


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BaseCoreVueProject/Home"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 上午9:55
收件人:&nbsp;"BaseCoreVueProject/Home"<Home@noreply.github.com&gt;;
抄送:&nbsp;"2923280915"<2923280915@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BaseCoreVueProject/Home] LJS.Core 申请加入 (#5)





 
你的博客有在线地址么，可以顺带推广下你的博客地址

**Comment by anjoy8** [comment]
好的，我先邀请你了，排队中，你趁着着这段时间（等发文应该有一个月还），正好你再完善下README.md，来两个图啥的，
最好有一个在线的博客页面，一个index页面也可以，调个api，你懂的，美观

**Comment by Lenceas** [comment]
ok,多谢老张




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ansonzhang"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 上午10:04
收件人: "BaseCoreVueProject/Home"<Home@noreply.github.com&gt;; 
抄送: "2923280915"<2923280915@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BaseCoreVueProject/Home] LJS.Core 申请加入 (#5)





 
好的，我先邀请你了，排队中，你趁着着这段时间（等发文应该有一个月还），正好你再完善下README.md，来两个图啥的，
 最好有一个在线的博客页面，一个index页面也可以，调个api，你懂的，美观

**Comment by anjoy8** [comment]
我帮你fork了，以后你自己可定期同步。
排队查看https://github.com/BaseCoreVueProject/Home/blob/main/README.md#%E6%8E%92%E9%98%9F%E6%83%85%E5%86%B5%E5%AE%89%E6%8E%92%E4%B8%AD%E6%9C%89%E5%88%A0%E5%87%8F%E5%8F%AF%E8%83%BD

**Comment by Lenceas** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ansonzhang"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 上午10:08
收件人: "BaseCoreVueProject/Home"<Home@noreply.github.com&gt;; 
抄送: "2923280915"<2923280915@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BaseCoreVueProject/Home] LJS.Core 申请加入 (#5)





 
我帮你fork了，以后你自己可定期同步。
 排队查看https://github.com/BaseCoreVueProject/Home/blob/main/README.md#%E6%8E%92%E9%98%9F%E6%83%85%E5%86%B5%E5%AE%89%E6%8E%92%E4%B8%AD%E6%9C%89%E5%88%A0%E5%87%8F%E5%8F%AF%E8%83%BD
