### ISSUE TITLE
SnailAspnetCoreFramework申请加入

### ISSUE THREAD

**Issue by shengyu-kmust** [BaseCoreVueProject/Home#6]
## 项目介绍
本项目定位为基于asp.net core的中小企业快速开发框架，包含完整的后端和前端的代码。
目前正在开发v2.0版本，v1.0版本可在分支里切换后直接运行，教程可参考我的系列博客，或是项目内的docs
后端技术栈：asp.net core 3.1,cap,swag,ef core code first,autofac,automapper,nlog,aop
前端技术栈：vue-element-admin,crud快速开发模块组件,mock
实现的功能：基于角色的权限控制，项目分层约定，代码自动生成，日志记录，性能监控，aop等
## 项目地址
https://github.com/shengyu-kmust/SnailAspNetCoreFramework
## 补充说明
* 将长期维护升级此项目
* 联系方式373087455@qq.com
* 此项目的公共组件用的是Snail开源项目，地址为https://github.com/shengyu-kmust/Snail

**Comment by anjoy8** [comment]
排队中，排队信息可以查看：https://github.com/BaseCoreVueProject/Home#%E6%8E%A8%E5%B9%BF%E6%96%B9%E6%A1%88。
